apps:
  archive_unpacker:
    command:
    - unz
    view_flag: -v
  audio_editor:
    command:
    - audacity
    daemon: true
  audio_player:
    command:
    - play
  doc_editor:
    command:
    - soffice
    daemon: true
  file_manager:
    command:
    - xdesktop
  image_editor:
    command:
    - gimp
    daemon: true
  image_viewer:
    command:
    - gqview
    daemon: true
  pdf_annotator:
    command:
    - xournal
    daemon: true
  pdf_viewer:
    command:
    - evince
    daemon: true
  text_editor:
    command:
    - xedit
    daemon: true
  video_player:
    command:
    - play
  web_browser:
    command:
    - firefox
bindings:
  .7z:
    open: archive_unpacker
    view: archive_unpacker
  .ace:
    open: archive_unpacker
    view: archive_unpacker
  .avi:
    open: video_player
  .bmp:
    open: image_editor
    view: image_viewer
  .bz2:
    open: archive_unpacker
    view: archive_unpacker
  .csv:
    open: doc_editor
  .deb:
    open: archive_unpacker
    view: archive_unpacker
  .dmg:
    open: archive_unpacker
    view: archive_unpacker
  .doc:
    open: doc_editor
  .docx:
    open: doc_editor
  .flv:
    open: video_player
  .gif:
    open: image_editor
    view: image_viewer
  .gpg:
    open: archive_unpacker
    view: archive_unpacker
  .gz:
    open: archive_unpacker
    view: archive_unpacker
  .heic:
    open: image_editor
    view: image_viewer
  .htm:
    open: text_editor
    view: web_browser
  .html:
    open: text_editor
    view: web_browser
  .iso:
    open: archive_unpacker
    view: archive_unpacker
  .jar:
    open: archive_unpacker
    view: archive_unpacker
  .jpeg:
    open: image_editor
    view: image_viewer
  .jpg:
    open: image_editor
    view: image_viewer
  .json:
    open: text_editor
  .lzma:
    open: archive_unpacker
    view: archive_unpacker
  .mp3:
    open: audio_editor
    view: audio_player
  .mp4:
    open: video_player
  .mpegts:
    open: video_player
  .odf:
    open: doc_editor
  .odg:
    open: doc_editor
  .odp:
    open: doc_editor
  .ods:
    open: doc_editor
  .odt:
    open: doc_editor
  .ogg:
    open: audio_editor
    view: audio_player
  .pcx:
    open: image_editor
    view: image_viewer
  .pdf:
    open: pdf_annotator
    view: pdf_viewer
  .png:
    open: image_editor
    view: image_viewer
  .ppt:
    open: doc_editor
  .pptx:
    open: doc_editor
  .rar:
    open: archive_unpacker
    view: archive_unpacker
  .rpm:
    open: archive_unpacker
    view: archive_unpacker
  .run:
    open: archive_unpacker
    view: archive_unpacker
  .sqlite:
    open: archive_unpacker
    view: archive_unpacker
  .svg:
    open: image_editor
    view: image_viewer
  .t7z:
    open: archive_unpacker
    view: archive_unpacker
  .tar:
    open: archive_unpacker
    view: archive_unpacker
  .tbz:
    open: archive_unpacker
    view: archive_unpacker
  .tgz:
    open: archive_unpacker
    view: archive_unpacker
  .tif:
    open: image_editor
    view: image_viewer
  .tiff:
    open: image_editor
    view: image_viewer
  .tlz:
    open: archive_unpacker
    view: archive_unpacker
  .txt:
    open: text_editor
  .txz:
    open: archive_unpacker
    view: archive_unpacker
  .tzs:
    open: archive_unpacker
    view: archive_unpacker
  .tzst:
    open: archive_unpacker
    view: archive_unpacker
  .wav:
    open: audio_editor
    view: audio_player
  .webm:
    open: video_player
  .webp:
    open: image_editor
    view: image_viewer
  .wpd:
    open: doc_editor
  .wsdl:
    open: doc_editor
  .xhtml:
    open: text_editor
    view: web_browser
  .xls:
    open: doc_editor
  .xlsx:
    open: doc_editor
  .xoj:
    open: pdf_annotator
  .xz:
    open: archive_unpacker
    view: archive_unpacker
  .yaml:
    open: text_editor
  .zip:
    open: archive_unpacker
    view: archive_unpacker
  .zst:
    open: archive_unpacker
    view: archive_unpacker
  .zstd:
    open: archive_unpacker
    view: archive_unpacker
parameters:
  homepage: http://drtuxwang.fast-page.org/bookmarks.xhtml
  image_extensions:
  - .bmp
  - .gif
  - .heic
  - .jpeg
  - .jpg
  - .pcx
  - .png
  - .svg
  - .tif
  - .tiff
  - .webp
  user_agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
  video_extensions:
  - .avi
  - .flv
  - .mp4
  - .mpegts
  - .webm
  web_mail: https://accounts.google.com/ServiceLogin?service=mail&continue=https://mail.google.com
  web_uri:
  - ftp
  - http
  - https
