docker_daemon: false
portable: false
sudo_commands: false
vm_9pnet: false
vm_guest: false
vm_host: false
vm_vboxsf: false
zram_swap: false

bin_directory: ../../bin
data2_mount: null

charge_start: 60
charge_stop: 80
