apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    helm.sh/chart: {{ include "chart.name" . }}
    app.kubernetes.io/name: {{ include "chart.name" . }}-servers
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "app.fullname" . }}-server
spec:
  replicas: {{ .Values.app.servers.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}-servers
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}-servers
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: {{ include "chart.image.name" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-box
        resources:
        volumeMounts:
        - mountPath: /shared
          name: shared
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /shared
        name: shared
  updateStrategy:
    type: RollingUpdate
